[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.28"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@layerzero/=lib/LayerZero-v2/",
    "@erc7579/=lib/erc7579-implementation/",
    "@kernel/=lib/kernel-7579-plugins/",
    "@chainlink/=lib/chainlink-brownie-contracts/"
]

optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# polygon = { key = "${POLYGONSCAN_API_KEY}" }
# optimism = { key = "${OPTIMISM_API_KEY}" }
# arbitrum = { key = "${ARBISCAN_API_KEY}" }
# base = { key = "${BASESCAN_API_KEY}" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

[doc]
out = "docs"
title = "FRVM Documentation"