[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "ease-dapp"

[services.variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"
NEXT_PUBLIC_VERCEL_URL = "${{ RAILWAY_PUBLIC_DOMAIN }}"